config/routes.rb
Wisp::Application.routes.draw do
  get "posts/index"

  match "posts/upload", :as => "upload"
  match "posts/delete", :as => "delete"

  root :to => 'posts#index'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController 
  def index
    @posts = AWS::S3::Bucket.find(Wisp::Application::BUCKET).objects
  end

  def upload
    begin
      AWS::S3::S3Object.store(sanitize_filename(params[:mp3file].original_filename), params[:mp3file].read, Wisp::Application::BUCKET, :access => :public_read)
      redirect_to root_path
    rescue
      render :text => "Couldn't complete the upload"
    end
  end

  def delete
    if (params[:post])
      AWS::S3::S3Object.find(params[:post], Wisp::Application::BUCKET).delete
      redirect_to root_path
    else
      render :text => "No post was found to delete!"
    end
  end

  private

  def sanitize_filename(file_name)
    just_filename = File.basename(file_name)
    just_filename.sub(/[^\w\.\-]/,'_')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def download_url_for(post_key)  
    	AWS::S3::S3Object.url_for(post_key, Wisp::Application::BUCKET, :authenticated => true)  
	end  
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/index/index.html.erb
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300' rel='stylesheet' type='text/css'>

<div class="container">
<!-- <img src="snake_icon_green.png" height="42" width="42">  -->
<h1>wisp <span>(sounds good)</span></h1>
<div class="post">
<a href="https://dl.dropboxusercontent.com/u/37786375/wisp/Memo2.m4a">construction</a>
posted by Dan
</div>
<div class="post">
<a href="https://dl.dropboxusercontent.com/u/37786375/wisp/Memo3.m4a">music majors</a>
posted by Dan
</div>
<div class="post">
<a href="https://dl.dropboxusercontent.com/u/37786375/wisp/Memo.m4a">damn</a>
posted by Kenyatta
</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

 
<link href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,400,300|Norican' rel='stylesheet' type='text/css'>
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<meta name="apple-mobile-web-app-capable" content="yes" />

<title>wisp</title>

	<%= stylesheet_link_tag    "application", :media => "all" %>
	<%= javascript_include_tag "application" %>
	<%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<!-- <script type="text/javascript" src="js/audiohack.js"></script>
<script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script> 
<script type="text/javascript" src="js/amazons3uploader.js"></script> -->

<!--
<script src="http://cwilso.github.io/AudioContext-MonkeyPatch/AudioContextMonkeyPatch.js"></script>
<script src="audiorecording/js/recorder.js"></script>
<script src="audiorecording/js/main.js"></script> 
-->



<div class="container">
<div class="bar">wisp (sounds good)</div>
<div class="content">

<% @posts.each do |post| %>  
	<div class="post">

		<%= post.metadata[:Name] %> from <%= post.metadata[:loc] %><br>
		<small>posted at <%= post.about[:date] %></small>

		<table>  
		<tr>
			<td><%= post.key %></td>

			<td><%= link_to "Download", download_url_for(post.key) %> or </td>
			<td><%= link_to "Delete", "posts/delete/?post=" + post.key, :confirm => 'Are you sure you want to delete ' + post.key + '?' %></td>
		</tr>
		</table> 
		<audio src=<%= download_url_for(post.key) %> controls>
		</audio>
	</div>
<% end %>  

<p>Upload a new MP3:</p>
<%= form_tag upload_path, :method => "post", :multipart => true do %>  
    <%= file_field_tag "oggfile" %>  
    <%= submit_tag "upload!" %>  
<% end %>  
</div>
</div>